<?= link_tag('assets/dashboard/css/pace-theme-flash.css','screen') ?>
<?= link_tag('assets/dashboard/css/bootstrap.min.css') ?>
<?= link_tag('assets/dashboard/css/bootstrap-theme.min.css') ?>
<?= link_tag('assets/dashboard/css/font-awesome.css') ?>
<?= link_tag('assets/dashboard/css/animate.min.css') ?>
<?= link_tag('assets/dashboard/css/perfect-scrollbar.css') ?>
<?= link_tag('assets/dashboard/css/orange.css','screen') ?>
<?= link_tag('assets/dashboard/css/jquery-ui.min.css','screen') ?>
<?= link_tag('assets/dashboard/css/style.css') ?>
<?= link_tag('assets/dashboard/css/responsive.css') ?>
<?= link_tag('assets/dashboard/css/jquery.dataTables.css') ?>
<?= link_tag('assets/dashboard/css/dataTables.responsive.css') ?>
<?= link_tag('assets/dashboard/css/dataTables.tableTools.min.css') ?>
<?= link_tag('assets/dashboard/css/dataTables.bootstrap.css') ?>
<?= link_tag('assets/dashboard/css/bootstrap-tagsinput.css') ?>
<?= link_tag('assets/dashboard/css/multi-select.css') ?>
<?= link_tag('assets/dashboard/css/messenger.css') ?>
<?= link_tag('assets/dashboard/css/messenger-theme-future.css') ?>
<?= link_tag('assets/dashboard/css/messenger-theme-flat.css') ?>
<?= link_tag('assets/dashboard/css/datepicker.css') ?>
<?= link_tag('assets/dashboard/css/skins/flat/_all.css','screen') ?>
<!-- <?= link_tag('assets/plugins/jquery-ui/smoothness/jquery-ui.min.css') ?> -->
<?= link_tag('assets/dashboard/css/switch.css') ?>
<link href="<?php echo base_url('assets/dashboard/css/bootstrap-colorpicker.min.css') ?>" rel="stylesheet" type="text/css" media="screen"/>
